// src/views/auth/LogIn.vue
<template>
    <Grid maxWidth="Md">
        <Row>
            <Column
                fluidHeight
                :bottomPadding="false"
                :md="6"
                :xs="12"
                :offset="{ md: 3 }"
            >
                <Box :mt="{ xs: 8, md: 12 }">
                    <Box :mb="1">
                        <Tex
                            size="Xl"
                            weight="Heavy"
                        >
                            Welcome back
                        </Tex>
                    </Box>

                    <Box :mb="4">
                        <Tex size="Sm">
                            Need an account?
                            <Ref
                                color="Gray1"
                                decoration="Underline"
                                size="Sm"
                                :to="{ name: 'Register', query: { email: this.email }}"
                            >
                                Sign up
                            </Ref>
                        </Tex>
                    </Box>

                    <Box
                        display="Flex"
                        el="Form"
                        flexDirection="Column"
                    >
                        <Box :mb="2">
                            <Field
                                v-model="email"
                                :isValid="!$v.email.$invalid"
                                autofocus
                                id="email"
                                label="Email"
                            />
                        </Box>

                        <Box :mb="2">
                            <Field
                                v-model="password"
                                :isValid="!$v.password.$invalid"
                                id="password"
                                label="Password"
                                type="Password"
                            />
                        </Box>

                        <Box fluidWidth>
                            <Button
                                color="Brand"
                                fluid
                                size="Lg"
                                textAlign="Left"
                                :disabled="$v.validationGroup.$invalid || loading"
                                :isLoading="loading"
                                :onClick="onClickLogIn"
                            >
                                Log In
                            </Button>
                        </Box>

                        <Box :mt="1">
                            <Tex
                                color="Gray5"
                                size="Xxs"
                            >
                                So splendid to see you again, Old Sport.
                            </Tex>
                        </Box>

                        <Box
                            v-if="error"
                            :mt="3"
                        >
                            <Tex
                                color="Red3"
                                size="Sm"
                            >
                                {{ error }}
                            </Tex>
                        </Box>
                    </Box>
                </Box>
            </Column>
        </Row>
    </Grid>
</template>

<script>
import { mapActions } from 'vuex'
import { email, required } from 'vuelidate/lib/validators'
import { get } from '@/utils'
import Box from '@/components/core/layout/Box'
import Button from '@/components/core/actions/Button'
import Column from '@/components/core/layout/Column'
import Field from '@/components/core/form/Field'
import Grid from '@/components/core/layout/Grid'
import Ref from '@/components/core/actions/Ref'
import Row from '@/components/core/layout/Row'
import Tex from '@/components/core/typography/Tex'

export default {
    name: 'LogIn',
    components: {
        Box,
        Button,
        Column,
        Field,
        Grid,
        Ref,
        Row,
        Tex,
    },
    props: {
        emailParam: {
            type: String,
        },
    },
    data() {
        return {
            email: get(() => this.emailParam),
            error: undefined,
            loading: false,
            password: undefined,
        }
    },
    methods: {
        ...mapActions(['LOG_IN_USER']),
        async onClickLogIn() {
            this.error = undefined
            this.loading = true
            try {
                await this.LOG_IN_USER({
                    email: this.email,
                    password: this.password,
                })
                this.$router.push({ name: 'Home' })
            } catch (err) {
                let error
                if ('email' in err) {
                    error = get(() => err.email[0])
                } else if ('password' in err) {
                    error = get(() => err.password[0])
                } else if ('non_field_errors' in err) {
                    error = get(() => err.non_field_errors[0])
                }
                this.loading = false
                this.error = error
            }
        },
    },
    validations: {
        email: {
            email,
            required,
        },
        password: {
            required,
        },
        validationGroup: ['email', 'password'],
    },
    metaInfo: {
        title: 'Log In',
    },
}
</script>

// src/pages/auth/Login/index.tsx
import React from "react";
import { inject, observer } from "mobx-react";
import DocumentTitle from "react-document-title";
import {
    Grid,
    Row,
    Col,
    Box,
    Text,
    Link,
    Field,
    Button
} from "../../../components";
import RootStore from "../../../store";
import { Redirect } from "react-router";
import { get } from "../../../lib/get";
import { parse } from "query-string";

interface Props {
    location: any;
    rootStore: RootStore;
}

class LogInClass extends React.Component<Props> {
    componentWillMount() {
        const {
            location,
            rootStore: {
                logInStore: { setEmail }
            }
        } = this.props;
        const queryParams = parse(location.search);
        const email = get(() => queryParams.email);
        if (email) setEmail(email);
    }

    componentWillUnmount() {
        this.props.rootStore.logInStore.reset();
    }

    onChangeEmail = (e: React.ChangeEvent<any>) => {
        this.props.rootStore.logInStore.setEmail(e.target.value);
    };

    onChangePassword = (e: React.ChangeEvent<any>) => {
        this.props.rootStore.logInStore.setPassword(e.target.value);
    };

    onSubmit = (e: React.FormEvent) => {
        e.preventDefault();
        this.props.rootStore.logInStore.logIn();
    };

    render() {
        const {
            location,
            rootStore: { logInStore, isAuthenticated }
        } = this.props;

        const queryParams = parse(location.search);
        const redirect = get(() => location.state.from) ||
            queryParams.redirect || { pathname: "/" };
        if (logInStore.redirectToReferrer || isAuthenticated) {
            return <Redirect to={redirect} />;
        }

        const { email, error, isLoading, password, validations } = logInStore;

        return (
            <DocumentTitle title="Log In | Wilbur">
                <Grid maxWidth="md">
                    <Row>
                        <Col
                            fluidHeight
                            bottomPadding={false}
                            md={6}
                            xs={12}
                            offset={{ md: 3 }}
                        >
                            <Box mt={{ xs: 8, md: 12 }}>
                                <Box mb={1}>
                                    <Text
                                        font={Text.Font.Title}
                                        size={Text.Size.Xl}
                                    >
                                        Welcome back
                                    </Text>
                                </Box>

                                <Box mb={4}>
                                    <Text size={Text.Size.Sm}>
                                        Need an account?{" "}
                                        <Link
                                            color={Link.Color.Gray1}
                                            decoration
                                            size={Text.Size.Sm}
                                            to={{
                                                pathname: "/register",
                                                search:
                                                    !!email && `?email=${email}`
                                            }}
                                        >
                                            Sign up
                                        </Link>
                                    </Text>
                                </Box>

                                <Box
                                    display={Box.Display.Flex}
                                    el={Box.Element.Form}
                                    flexDirection={Box.FlexDirection.Column}
                                    onSubmit={this.onSubmit}
                                >
                                    <Box mb={2}>
                                        <Field
                                            autocomplete="username email"
                                            autofocus
                                            id="email"
                                            label="Email"
                                            value={email}
                                            onChange={this.onChangeEmail}
                                        />
                                    </Box>

                                    <Box mb={2}>
                                        <Field
                                            autocomplete="current-password"
                                            id="password"
                                            label="Password"
                                            onChange={this.onChangePassword}
                                            type={Field.Type.Password}
                                            value={password}
                                        />
                                    </Box>

                                    <Box fluidWidth>
                                        <Button
                                            color={Button.Color.Brand}
                                            disabled={!validations.all.valid}
                                            fluid
                                            isLoading={isLoading}
                                            size={Button.Size.Md}
                                            textAlign={Button.TextAlign.Left}
                                            type="submit"
                                        >
                                            Log In
                                        </Button>
                                    </Box>

                                    <Box mt={1}>
                                        <Text
                                            color={Text.Color.Gray5}
                                            size={Text.Size.Xxs}
                                        >
                                            Splendid to see you again, Old
                                            Sport.
                                        </Text>
                                    </Box>

                                    {!!error && (
                                        <Box mt={3}>
                                            <Text
                                                color={Text.Color.Red3}
                                                size={Text.Size.Sm}
                                            >
                                                {error}
                                            </Text>
                                        </Box>
                                    )}
                                </Box>
                            </Box>
                        </Col>
                    </Row>
                </Grid>
            </DocumentTitle>
        );
    }
}

export const LogIn = inject("rootStore")(observer(LogInClass));
