// src/pages/Budgets/components/Table/index.tsx
import React from "react";
import styled from "styled-components";
import { Box, Text } from "../../../../components";
import { Budget } from "../../../../types/budget";
import TableRow from "../TableRow";

interface Props {
    budgets: Array<Budget>;
}

export default class Table extends React.Component<Props> {
    render() {
        const { budgets } = this.props;
        return (
            <Box
                bt
                borderColor={Box.BorderColor.Gray8}
                css={`
                    overflow-x: scroll;
                `}
            >
                <StyledTable>
                    <StyledTableHeader>
                        <tr>
                            <th>&nbsp;</th>
                            <th>
                                <Text
                                    align={Text.Align.Right}
                                    color={Text.Color.Gray3}
                                    size={Text.Size.Xxs}
                                    transform={Text.Transform.Uppercase}
                                    weight={Text.Weight.Bold}
                                >
                                    Remaining
                                </Text>
                            </th>
                            <th>
                                <Text
                                    align={Text.Align.Right}
                                    color={Text.Color.Gray3}
                                    size={Text.Size.Xxs}
                                    transform={Text.Transform.Uppercase}
                                    weight={Text.Weight.Bold}
                                >
                                    Spent
                                </Text>
                            </th>
                            <th>
                                <Text
                                    align={Text.Align.Right}
                                    color={Text.Color.Gray3}
                                    size={Text.Size.Xxs}
                                    transform={Text.Transform.Uppercase}
                                    weight={Text.Weight.Bold}
                                >
                                    Budgeted
                                </Text>
                            </th>
                        </tr>
                    </StyledTableHeader>
                    <tbody>
                        {budgets.map(budget => (
                            <TableRow
                                key={budget.id}
                                id={budget.id}
                                name={budget.name}
                                budget={budget}
                                budgeted={budget.budgeted}
                                spent={budget.spent}
                            />
                        ))}
                    </tbody>
                </StyledTable>
            </Box>
        );
    }
}

const StyledTable = styled.table`
    border-collapse: separate;
    border-spacing: 0;
    width: 100%;
`;

const StyledTableHeader = styled.thead`
    background-color: ${props => props.theme.colors.gray10};
    th {
        border-bottom: 1px solid ${props => props.theme.colors.gray8};
        padding: 0.7rem 1rem;
        word-break: normal;
    }
`;

// src/views/Budgets/components/Table/index.vue
<template>
    <Box
        bt
        borderColor="Gray8"
        :css="`
            overflow-x: scroll;
        `"
    >
        <StyledTable>
            <StyledTableHeader>
                <tr>
                    <th>&nbsp;</th>
                    <th>
                        <Tex
                            align="Right"
                            color="Gray2"
                            size="Xs"
                            weight="Bold"
                        >
                            Remaining
                        </Tex>
                    </th>
                    <th>
                        <Tex
                            align="Right"
                            color="Gray2"
                            size="Xs"
                            weight="Bold"
                        >
                            Spent
                        </Tex>
                    </th>
                    <th>
                        <Tex
                            align="Right"
                            color="Gray2"
                            size="Xs"
                            weight="Bold"
                        >
                            Budgeted
                        </Tex>
                    </th>
                </tr>
            </StyledTableHeader>
            <Draggable
                :options="draggableOptions"
                :value="budgets"
                element="tbody"
                @change="onDragChange($event)"
            >
                <TableRow
                    v-for="budget in budgets"
                    :key="budget.id"
                    :id="budget.id"
                    :name="budget.name"
                    :budget="budget"
                    :budgeted="budget.budgeted"
                    :activity="budget.activity"
                    :remaining="budget.remaining"
                    :transactionCount="budget.transaction_count"
                    :creationDate="budget.date_created"
                />
            </Draggable>
        </StyledTable>
    </Box>
</template>

<script>
import draggable from 'vuedraggable'
import { get } from '@/utils'
import Box from '@/components/core/layout/Box'
import Tex from '@/components/core/typography/Tex'
import TableRow from '../TableRow'
import { StyledTable, StyledTableHeader } from './styled-components'

export default {
    name: 'BudgetsTable',
    components: {
        Box,
        StyledTable,
        StyledTableHeader,
        TableRow,
        Tex,
        Draggable: draggable,
    },
    props: {
        budgets: {
            default: () => [],
            type: Array,
        },
    },
    data: () => ({
        draggableOptions: {
            handle: '.handle',
        },
    }),
    methods: {
        onDragChange(event) {
            const moved = event.moved
            const data = {
                budgetId: moved.element.id,
                newIndex: moved.newIndex,
                oldIndex: moved.oldIndex,
            }
            this.$emit('handleOnReorderBudgets', data)
        },
    },
}
</script>
