// src/components/ui/Navbar/index.vue
<template>
    <Box
        alignItems="Center"
        bb
        backgroundColor="White"
        borderColor="Gray9"
        el="Nav"
        display="Flex"
        fluidWidth
        justifyContent="SpaceBetween"
        :pv="1.25"
    >
        <Box
            alignItems="Baseline"
            display="Flex"
            fluidHeight
            :pt="0.5"
        >
            <StyledLink
                :active="$route.name === 'Home'"
                :to="{ name: 'Home'}"
            >
                Budgets
            </StyledLink>
            <StyledLink
                v-if="false"
                :active="$route.name === 'Transactions'"
                :to="{ name: 'Transactions'}"
            >
                Transactions
            </StyledLink>
        </Box>
        <Box
            display="Flex"
            fluidHeight
        >
            <Box
                alignItems="Center"
                display="Flex"
                position="Relative"
            >
                <StyledUserContainer
                    v-click-outside="onClickOutsideDropdown"
                    :active="isDropDownOpen"
                    @click="onClickToggleDropdown"
                >
                    <Box
                        alignItems="Center"
                        b
                        backgroundColor="Gold2"
                        borderColor="Gold1"
                        cornerRadius="Circle"
                        display="Flex"
                        justifyContent="Center"
                        :css="`
                            height: 2rem;
                            width: 2rem;
                        `"
                    >
                        <Tex
                            color="White"
                            el="Span"
                            size="Md"
                            transform="Uppercase"
                            weight="Bold"
                        >{{initial}}</Tex>
                    </Box>
                    <ChevronDownIcon />
                </StyledUserContainer>

                <StyledDropdown :open="isDropDownOpen">
                    <StyledDropdownItem v-if="false">
                        <Tex
                            color="Gray2"
                            size="Xs"
                        >
                            <router-link :to="{ name: 'Accounts'}">Connected Accounts</router-link>
                        </Tex>
                    </StyledDropdownItem>
                    <StyledDropdownItem>
                        <button @click="onClickLogOut">
                            <Tex
                                color="Gray2"
                                size="Xs"
                            >
                                Log Out
                            </Tex>
                        </button>
                    </StyledDropdownItem>
                </StyledDropdown>
            </Box>
        </Box>
    </Box>
</template>

<script>
import { mapActions, mapGetters } from 'vuex'
import { get } from '@/utils'
import ChevronDownIcon from '@/assets/icons/chevron-down.svg'
import Logo from '@/assets/icons/logo.svg'
import Box from '@/components/core/layout/Box'
import Tex from '@/components/core/typography/Tex'
import {
    StyledLink,
    StyledUserContainer,
    StyledDropdown,
    StyledDropdownItem,
} from './styled-components'

export default {
    name: 'Navbar',
    components: {
        Box,
        ChevronDownIcon,
        Logo,
        StyledDropdown,
        StyledDropdownItem,
        StyledLink,
        StyledUserContainer,
        Tex,
    },
    data: () => ({
        isDropDownOpen: false,
    }),
    computed: {
        ...mapGetters(['user']),
        initial() {
            return (
                get(() => this.user.first_name[0]) ||
                get(() => this.user.email[0])
            )
        },
    },
    methods: {
        ...mapActions(['LOG_OUT_USER']),
        onClickToggleDropdown() {
            this.isDropDownOpen = !this.isDropDownOpen
        },
        onClickOutsideDropdown() {
            if (this.isDropDownOpen) this.isDropDownOpen = false
        },
        async onClickLogOut() {
            await this.LOG_OUT_USER()
            this.$router.push({ name: 'LogIn' })
        },
    },
}
</script>

// src/components/core/app/Navbar/index.tsx
import * as React from "react";
import OutsideClickHandler from "react-outside-click-handler";
import { css } from "styled-components";

import { cssFactory } from "../../../utils/styled-components";
import { Link } from "../../actions/Link";
import { CaretDown, Icon } from "../../icons/Icon";
import { Box } from "../../layout/Box";
import { Col } from "../../layout/Col";
import { Grid } from "../../layout/Grid";
import { Row } from "../../layout/Row";
import { Text } from "../../typography/Text";

import Dropdown from "./components/Dropdown";

interface Props {
    location: any;
    userInitial: string;
    handleLogOut: () => Promise<void>;
}

export class Navbar extends React.Component<Props> {
    public state = { isDropdownOpen: false };

    public getLinkProps = (path: string) => {
        const {
            location: { pathname }
        } = this.props;
        const active = path === pathname;
        return {
            color: active ? Text.Color.Gray1 : Text.Color.Gray5,
            weight: active ? Text.Weight.SemiBold : Text.Weight.Normal
        };
    };

    public onOutsideClick = () => {
        this.setState({ isDropdownOpen: false });
    };

    public onClickDropdown = () => {
        this.setState({
            isDropdownOpen: !this.state.isDropdownOpen
        });
    };

    public render() {
        const { userInitial, handleLogOut } = this.props;
        const { isDropdownOpen } = this.state;
        return (
            <Box
                backgroundColor={Box.BackgroundColor.White}
                bb
                borderColor={Box.BorderColor.Gray9}
                css={genNavbarOuterCSS()}
                el={Box.Element.Nav}
                position={Box.Position.Fixed}
            >
                <Grid maxWidth="md" ph={{ xs: 2, md: 10 }}>
                    <Row>
                        <Col bottomPadding={false} fluidHeight xs={12}>
                            <Box
                                alignItems={Box.AlignItems.Center}
                                css={genNavbarInnerCSS()}
                                display={Box.Display.Flex}
                                justifyContent={Box.JustifyContent.SpaceBetween}
                            >
                                <Box
                                    alignItems={Box.AlignItems.Baseline}
                                    display={Box.Display.Flex}
                                    pt={0.5}
                                >
                                    <Box>
                                        <Link to="/budgets">
                                            <Text
                                                {...this.getLinkProps(
                                                    "/budgets"
                                                )}
                                                size={Text.Size.Sm}
                                            >
                                                Budgets
                                            </Text>
                                        </Link>
                                    </Box>
                                    <Box ml={3}>
                                        <Link to="/transactions">
                                            <Text
                                                {...this.getLinkProps(
                                                    "/transactions"
                                                )}
                                                size={Text.Size.Sm}
                                            >
                                                Transactions
                                            </Text>
                                        </Link>
                                    </Box>
                                </Box>
                                <Box
                                    alignItems={Box.AlignItems.Center}
                                    display={Box.Display.Flex}
                                    position={Box.Position.Relative}
                                >
                                    <OutsideClickHandler
                                        disabled={!isDropdownOpen}
                                        onOutsideClick={this.onOutsideClick}
                                    >
                                        <Box
                                            alignItems={Box.AlignItems.Center}
                                            display={Box.Display.Flex}
                                            pt={0.5}
                                            onClick={this.onClickDropdown}
                                        >
                                            <Box
                                                alignItems={
                                                    Box.AlignItems.Center
                                                }
                                                display={Box.Display.Flex}
                                                b
                                                backgroundColor={
                                                    Box.BackgroundColor.Gold4
                                                }
                                                borderColor={
                                                    Box.BorderColor.Gold1
                                                }
                                                cornerRadius={
                                                    Box.CornerRadius.Circle
                                                }
                                                justifyContent={
                                                    Box.JustifyContent.Center
                                                }
                                                css={genAvatarCSS()}
                                                mr={0.25}
                                            >
                                                <Text
                                                    color={Text.Color.White}
                                                    el={Text.Element.Span}
                                                    transform={
                                                        Text.Transform.Uppercase
                                                    }
                                                    weight={Text.Weight.Bold}
                                                >
                                                    {userInitial}
                                                </Text>
                                            </Box>
                                            <Box mt={0.7}>
                                                <CaretDown
                                                    color={Icon.Color.Gray6}
                                                    size={Icon.Size.Xs}
                                                />
                                            </Box>
                                        </Box>
                                    </OutsideClickHandler>
                                    <Dropdown
                                        open={isDropdownOpen}
                                        handleLogOut={handleLogOut}
                                    />
                                </Box>
                            </Box>
                        </Col>
                    </Row>
                </Grid>
            </Box>
        );
    }
}

const genNavbarOuterCSS = () =>
    cssFactory(css)`
        left: 0;
        right: 0;
        top: 0
        z-index: ${props => props.theme.zIndex.Z_INDEX_HIGHEST};
    `;

const genNavbarInnerCSS = () =>
    cssFactory(css)`
        height: 3.5rem;
    `;

const genAvatarCSS = () =>
    cssFactory(css)`
        height: 2rem;
        width: 2rem;
    `;
