// src/views/Budgets/components/TableRow/index.vue
<template>
    <StyledTableRow>
        <StyledTableRowName>
            <Box
                alignItems="Center"
                display="Flex"
                :css="`
                    a { text-decoration: none; }
                `"
            >
                <StyledIconContainer class="handle">
                    <MoreVerticalIcon />
                </StyledIconContainer>
                <Tex
                    color="Blue2"
                    size="Sm"
                    weight="SemiBold"
                >
                    <router-link
                        :to="{ name: 'Budget', params: { id: id, budget }}"
                        class="budgets-table-row__button"
                    >
                        {{name}}
                    </router-link>
                </Tex>
            </Box>
        </StyledTableRowName>

        <StyledTableData>
            <Tex
                align="Right"
                size="Sm"
            >${{remaining | prettyNumber}}</Tex>
        </StyledTableData>

        <StyledTableData>
            <Tex
                align="Right"
                size="Sm"
            >${{activity | prettyNumber}}</Tex>
        </StyledTableData>

        <StyledTableData>
            <Tex
                align="Right"
                size="Sm"
            >${{budgeted | prettyNumber}}</Tex>
        </StyledTableData>
    </StyledTableRow>
</template>

<script>
import MoreVerticalIcon from '@/assets/icons/more-vertical.svg'
import Box from '@/components/core/layout/Box'
import Tex from '@/components/core/typography/Tex'
import {
    StyledTableRow,
    StyledTableRowName,
    StyledTableData,
    StyledIconContainer,
} from './styled-components'

export default {
    name: 'TableRow',
    components: {
        Box,
        StyledIconContainer,
        MoreVerticalIcon,
        StyledTableData,
        StyledTableRow,
        StyledTableRowName,
        Tex,
    },
    props: {
        id: {
            type: String,
        },
        name: {
            type: String,
            required: true,
        },
        budget: {
            type: Object,
            required: true,
        },
        budgeted: {
            type: Number,
            required: true,
        },
        activity: {
            type: Number,
            required: true,
        },
        remaining: {
            type: Number,
            required: true,
        },
        transactionCount: {
            type: Number,
            required: true,
        },
    },
}
</script>

// src/pages/Budgets/components/TableRow/index.tsx
import React from "react";
import styled from "styled-components";
import { Text, Link } from "../../../../components";
import { prettyNumber } from "../../../../utils";
import { Budget } from "../../../../types/budget";
import { toJS } from "mobx";

interface Props {
    id: string;
    name: string;
    budget: Budget;
    budgeted?: number;
    spent?: number;
}

export default class TableRow extends React.Component<Props> {
    render() {
        const { id, name, budget, budgeted, spent } = this.props;
        const remaining = (budgeted as number) - (spent as number);
        return (
            <StyledTableRow>
                <StyledTableData>
                    <Link
                        color={Link.Color.Blue2}
                        size={Link.Size.Sm}
                        to={{
                            pathname: `/budgets/${id}`,
                            state: { budget: toJS(budget) }
                        }}
                        weight={Link.Weight.SemiBold}
                    >
                        {name}
                    </Link>
                </StyledTableData>

                <StyledTableData>
                    <Text align={Text.Align.Right} size={Text.Size.Sm}>
                        {prettyNumber(remaining)}
                    </Text>
                </StyledTableData>

                <StyledTableData>
                    <Text align={Text.Align.Right} size={Text.Size.Sm}>
                        {prettyNumber(spent as number)}
                    </Text>
                </StyledTableData>

                <StyledTableData>
                    <Text align={Text.Align.Right} size={Text.Size.Sm}>
                        ${prettyNumber(budgeted as number)}
                    </Text>
                </StyledTableData>
            </StyledTableRow>
        );
    }
}

const StyledTableRow = styled.tr`
    &:last-child {
        td {
            border-bottom: 0;
        }
    }

    td {
        border-bottom: 1px solid ${props => props.theme.colors.gray8};
        padding-bottom: 1rem;
        padding-top: 1rem;
        &:first-child {
            border-right: 1px solid ${props => props.theme.colors.gray9};
        }
    }
`;

const StyledTableData = styled.td`
    padding-left: 1.5rem;
    padding-right: 1.5rem;
`;
