// src/components/PasswordFeatures.vue
<template>
    <div class="password-features">
        <ul class="password-features__list">
            <li
                :class="['password-features__item', {
                success: hasLowercaseLetter
            }]"
            >One lowercase letter</li>
            <li
                :class="['password-features__item', {
                success: hasUppercaseLetter
            }]"
            >One uppercase letter</li>
        </ul>
        <ul class="password-features__list">
            <li
                :class="['password-features__item', {
                success: hasNumber
            }]"
            >One number</li>
            <li
                :class="['password-features__item', {
                success: isMinLength
            }]"
            >8 characters minimum</li>
        </ul>
    </div>
</template>

<script>
export default {
    name: 'PasswordFeatures',
    props: {
        hasLowercaseLetter: {
            required: true,
            type: Boolean,
        },
        hasUppercaseLetter: {
            required: true,
            type: Boolean,
        },
        hasNumber: {
            required: true,
            type: Boolean,
        },
        isMinLength: {
            required: true,
            type: Boolean,
        },
    },
}
</script>

<style lang="scss" scoped>
@import '../assets/styles/variables';
@import '../assets/styles/functions';
@import '../assets/styles/mixins';

.password-features {
    @include flex-column;
    @include respond-to(sm) {
        @include flex-row;
    }
    margin: {
        bottom: 1rem;
        top: -0.25rem;
    }
}

.password-features__list {
    list-style-type: none;
    margin: {
        bottom: 0;
        right: 2.5rem;
        top: 0;
    }
    padding-left: 0;
}

.password-features__item {
    @include flex-row;
    align-items: center;
    font: {
        family: $font-sans;
        size: 0.75rem;
    }
    margin-bottom: 0.25rem;
    transition: {
        duration: $transition-duration;
        property: opacity;
    }

    &:before {
        background-color: color(default, background, primary);
        border-radius: 8px;
        content: '';
        display: inline-block;
        height: 8px;
        margin-right: 0.5rem;
        min-height: 8px;
        min-width: 8px;
        width: 8px;
    }

    &.success {
        opacity: 0.35;
    }
}
</style>

// src/components/core/app/PasswordFeatures/index.tsx
import * as React from "react";
import styled, { css } from "styled-components";

import { style } from "../../../utils/css";
import { cssFactory } from "../../../utils/styled-components";
import { Box } from "../../layout/Box";
import { Text } from "../../typography/Text";

interface Props {
    hasLowercaseLetter: boolean;
    hasUppercaseLetter: boolean;
    hasNumber: boolean;
    isMinLength: boolean;
}

export class PasswordFeatures extends React.Component<Props> {
    public render() {
        const {
            hasLowercaseLetter,
            hasUppercaseLetter,
            hasNumber,
            isMinLength
        } = this.props;
        return (
            <Box
                display={Box.Display.Flex}
                flexDirection={{
                    xs: Box.FlexDirection.Column,
                    sm: Box.FlexDirection.Row
                }}
            >
                <Box mr={3}>
                    <StyledPasswordFeature success={hasLowercaseLetter}>
                        <Text size={Text.Size.Xs}>One lowercase letter</Text>
                    </StyledPasswordFeature>
                    <StyledPasswordFeature success={hasUppercaseLetter}>
                        <Text size={Text.Size.Xs}>One uppercase letter</Text>
                    </StyledPasswordFeature>
                </Box>
                <Box>
                    <StyledPasswordFeature success={hasNumber}>
                        <Text size={Text.Size.Xs}>One number</Text>
                    </StyledPasswordFeature>
                    <StyledPasswordFeature success={isMinLength}>
                        <Text size={Text.Size.Xs}>8 characters minimum</Text>
                    </StyledPasswordFeature>
                </Box>
            </Box>
        );
    }
}

interface StyledAnchorProps {
    success: boolean;
}

const styles = cssFactory<StyledAnchorProps>(css)`
    align-items: center;
    display: flex;
    margin-bottom: 0.25rem;
    ${props => style("opacity", 0.35, props.success)};
    transition: opacity 125ms;
    &:before {
        ${props => style("backgroundColor", props.theme.colors.green3)};
        border-radius: 8px;
        content: '';
        display: inline-block;
        height: 8px;
        margin-right: 0.5rem;
        margin-top: 0.1rem;
        min-height: 8px;
        min-width: 8px;
        width: 8px;
    }
`;

const StyledPasswordFeature = styled.div`
    ${styles};
`;
