// src/pages/Budget/index.tsx
import React from "react";
import { inject, observer } from "mobx-react";
import DocumentTitle from "react-document-title";
import OutsideClickHandler from "react-outside-click-handler";
import {
    Box,
    Col,
    Text,
    Grid,
    Row,
    Field,
    Button,
    Link
} from "../../components";
import RootStore from "../../store";
import { get } from "../../lib/get";

interface Props {
    location: any;
    match: any;
    history: any;
    rootStore: RootStore;
}

class BudgetClass extends React.Component<Props> {
    async componentWillMount() {
        const {
            history,
            match: {
                params: { id }
            },
            location: { state },
            rootStore: {
                budgetFormStore: { initForm, getBudget, setId },
                budgetsStore: { budgets, getBudgets }
            }
        } = this.props;
        setId(id);
        if (id !== "new") {
            const budget = get(() => state.budget);
            if (budget) {
                const amountCents = budget.budgeted;
                initForm(amountCents, budget.name, budget.description);
            } else {
                try {
                    await getBudget();
                } catch (e) {
                    history.replace("/budgets");
                }
            }
        }
        if (budgets.length) {
            return;
        }
        getBudgets();
    }

    componentWillUnmount() {
        this.props.rootStore.budgetFormStore.reset();
    }

    onChangeName = (e: React.ChangeEvent<any>) => {
        this.props.rootStore.budgetFormStore.setName(e.target.value);
    };

    onChangeAmount = (e: React.ChangeEvent<any>) => {
        this.props.rootStore.budgetFormStore.setAmount(e.target.value);
    };

    onChangeDescription = (e: React.ChangeEvent<any>) => {
        this.props.rootStore.budgetFormStore.setDescription(e.target.value);
    };

    onSubmit = async (e: React.FormEvent) => {
        e.preventDefault();
        const {
            history,
            rootStore: {
                budgetFormStore: { isUpdatable, handleUpdate, handleCreate }
            }
        } = this.props;
        if (isUpdatable) {
            handleUpdate();
            history.push("/budgets");
        } else {
            await handleCreate();
            history.push("/budgets");
        }
    };

    onOutsideClick = () => {
        this.props.rootStore.budgetFormStore.handleOutsideClick();
    };

    onClickDelete = async () => {
        const {
            history,
            rootStore: {
                budgetFormStore: { handleDelete, startDelete }
            }
        } = this.props;
        await handleDelete();
        if (startDelete) {
            history.push("/budgets");
        }
    };

    render() {
        const {
            rootStore: {
                budgetFormStore: {
                    name,
                    amount,
                    description,
                    error,
                    isUpdatable,
                    isLoading,
                    isDeleting,
                    networkActive,
                    startDelete,
                    validations,
                    amountError,
                    nameError
                }
            }
        } = this.props;
        const title = `${isUpdatable ? "Update" : "Create"} Budget`;
        return (
            <DocumentTitle title={`${title} | Wilbur`}>
                <Grid maxWidth="md" ph={{ xs: 2, md: 10 }}>
                    <Row>
                        <Col xs={12}>
                            <Box
                                alignItems={Box.AlignItems.Center}
                                css={`
                                    height: 2.3125rem;
                                `}
                                display={Box.Display.Flex}
                                mb={4}
                                mt={12}
                            >
                                <Text
                                    el={Text.Element.H1}
                                    font={Text.Font.Title}
                                    noMargin
                                    size={Text.Size.Xxl}
                                >
                                    {title}
                                </Text>
                            </Box>
                        </Col>
                    </Row>
                    <Row>
                        <Col xs={12}>
                            <Box
                                display={Box.Display.Flex}
                                el={Box.Element.Form}
                                flexDirection={Box.FlexDirection.Column}
                                onSubmit={this.onSubmit}
                            >
                                <Box mb={2}>
                                    <Field
                                        autofocus
                                        error={nameError}
                                        id="Name"
                                        label="Name"
                                        value={name}
                                        onChange={this.onChangeName}
                                    />
                                </Box>

                                <Box mb={2}>
                                    <Field
                                        error={amountError}
                                        id="amount"
                                        label="Amount"
                                        type={Field.Type.Number}
                                        value={amount || ""}
                                        onChange={this.onChangeAmount}
                                    />
                                </Box>

                                <Box mb={4}>
                                    <Field
                                        id="description"
                                        label="Description"
                                        type={Field.Type.Textarea}
                                        value={description}
                                        onChange={this.onChangeDescription}
                                    />
                                </Box>

                                <Box
                                    display={Box.Display.Flex}
                                    justifyContent={
                                        Box.JustifyContent.SpaceBetween
                                    }
                                >
                                    <Box display={Box.Display.Flex}>
                                        <Button
                                            color={Button.Color.Brand}
                                            disabled={
                                                !validations.all.valid ||
                                                !validations.all.dirty ||
                                                networkActive
                                            }
                                            isLoading={isLoading}
                                            size={Button.Size.Md}
                                            type="submit"
                                        >
                                            {isUpdatable ? "Update" : "Create"}
                                        </Button>
                                        <Box
                                            alignItems={Box.AlignItems.Center}
                                            display={Box.Display.Flex}
                                            ml={3}
                                        >
                                            <Link
                                                disabled={networkActive}
                                                size={Link.Size.Sm}
                                                to="/budgets"
                                            >
                                                Cancel
                                            </Link>
                                        </Box>
                                    </Box>

                                    {isUpdatable && (
                                        <OutsideClickHandler
                                            onOutsideClick={this.onOutsideClick}
                                        >
                                            <Button
                                                color={Button.Color.Error}
                                                disabled={networkActive}
                                                isLoading={isDeleting}
                                                noBackground
                                                size={Button.Size.Md}
                                                onClick={this.onClickDelete}
                                            >
                                                {startDelete
                                                    ? "Really delete?"
                                                    : "Delete"}
                                            </Button>
                                        </OutsideClickHandler>
                                    )}
                                </Box>

                                {!!error && (
                                    <Box mt={3}>
                                        <Text
                                            color={Text.Color.Red3}
                                            size={Text.Size.Sm}
                                        >
                                            {error}
                                        </Text>
                                    </Box>
                                )}
                            </Box>
                        </Col>
                    </Row>
                </Grid>
            </DocumentTitle>
        );
    }
}

export const Budget = inject("rootStore")(observer(BudgetClass));

// src/views/Budget/index.vue
<template>
    <Grid
        maxWidth="Md"
        :ph="{ xs: 2, md: 12 }"
    >
        <Row>
            <Column :xs="12">
                <Navbar />
            </Column>
        </Row>

        <Row>
            <Column :xs="12">
                <Box
                    alignItems="Center"
                    display="Flex"
                    justifyContent="SpaceBetween"
                    :mv="3"
                >
                    <Tex
                        el="H1"
                        noMargin
                        size="Xxl"
                    >
                        {{title}}
                    </Tex>
                </Box>
            </Column>
        </Row>

        <Row>
            <Column :xs="8">
                <Box
                    display="Flex"
                    el="Form"
                    flexDirection="Column"
                >
                    <Box
                        v-if="error"
                        :mt="3"
                    >
                        <Tex
                            color="Red3"
                            size="Sm"
                        >
                            {{ error }}
                        </Tex>
                    </Box>

                    <Box :mb="2">
                        <Field
                            v-model="name"
                            :error="nameError"
                            autofocus
                            id="name"
                            label="Name"
                        />
                    </Box>
                    <Box :mb="2">
                        <Field
                            v-model="amount"
                            :error="amountError"
                            id="amount"
                            label="Amount"
                            type="Number"
                        />
                    </Box>

                    <Box
                        display="Flex"
                        justifyContent="SpaceBetween"
                    >
                        <Box
                            alignItems="Center"
                            display="Flex"
                        >
                            <Button
                                v-if="isUpdatable"
                                color="Brand"
                                size="Lg"
                                :disabled="$v.validationGroup.$invalid || networkActive"
                                :isLoading="loading"
                                :onClick="onClickUpdate"
                            >
                                Update
                            </Button>
                            <Button
                                v-else
                                color="Brand"
                                size="Lg"
                                :disabled="$v.validationGroup.$invalid || networkActive"
                                :isLoading="loading"
                                :onClick="onClickCreate"
                            >
                                Create
                            </Button>
                            <Box :ml="3">
                                <Ref
                                    color="Gray4"
                                    size="Sm"
                                    :disabled="networkActive"
                                    :to="{ name: 'Home' }"
                                >
                                    Cancel
                                </Ref>
                            </Box>
                        </Box>

                        <Button
                            v-if="isUpdatable"
                            color="Error"
                            noBackground
                            size="Lg"
                            v-click-outside="resetDelete"
                            :disabled="networkActive"
                            :isLoading="deleting"
                            :onClick="onClickDelete"
                        >
                            {{ deleteButtonText }}
                        </Button>
                    </Box>
                </Box>
            </Column>
        </Row>
    </Grid>
</template>

<script>
import { mapActions } from 'vuex'
import { minValue, required } from 'vuelidate/lib/validators'
import { formatDateRange, get, toAmount, toCents } from '@/utils'
import api from '@/api'
import Box from '@/components/core/layout/Box'
import Button from '@/components/core/actions/Button'
import Column from '@/components/core/layout/Column'
import Field from '@/components/core/form/Field'
import Navbar from '@/components/ui/Navbar'
import Grid from '@/components/core/layout/Grid'
import Ref from '@/components/core/actions/Ref'
import Row from '@/components/core/layout/Row'
import Tex from '@/components/core/typography/Tex'

export default {
    name: 'Budget',
    components: {
        Box,
        Button,
        Column,
        Navbar,
        Field,
        Grid,
        Ref,
        Row,
        Tex,
    },
    props: {
        budget: {
            type: Object,
        },
        id: {
            type: String,
        },
    },
    data() {
        return {
            error: undefined,
            deleting: false,
            loading: false,
            amount: get(() => toAmount(this.budget.amount_cents)),
            name: get(() => this.budget.name),
            startDelete: false,
        }
    },
    computed: {
        amountError() {
            let error = undefined
            if (!this.$v.amount.required) {
                error = 'Amount is required'
            } else if (!this.$v.amount.minValue) {
                error = 'Amount must be positive'
            }
            return error
        },
        nameError() {
            let error = undefined
            if (!this.$v.name.required) {
                error = 'Name is required'
            }
            return error
        },
        deleteButtonText() {
            let text
            if (this.startDelete) {
                text = 'Really delete?'
            } else {
                text = 'Delete'
            }
            return text
        },
        isUpdatable() {
            return this.id !== 'new'
        },
        networkActive() {
            return this.loading || this.deleting
        },
        title() {
            if (this.isUpdatable) {
                return 'Update Budget'
            } else {
                return 'Create Budget'
            }
        },
    },
    async beforeRouteEnter(to, from, next) {
        const budgetId = get(() => to.params.id)
        if (budgetId === 'new') {
            next()
        } else {
            try {
                const res = await api.getBudget(budgetId)
                const budget = get(() => res.data)
                next(vm => vm.initData(budget))
            } catch (err) {
                next(vm => vm.$router.replace({ name: 'Home' }))
            }
        }
    },
    async beforeRouteUpdate(to, from, next) {
        const budgetId = get(() => to.params.id)
        if (budgetId === 'new') {
            next()
        } else {
            try {
                const res = await api.getBudget(budgetId)
                const budget = get(() => res.data)
                this.initData(budget)
                next()
            } catch (err) {
                next(vm => vm.$router.replace({ name: 'Home' }))
            }
        }
    },
    methods: {
        ...mapActions(['CREATE_BUDGET', 'DELETE_BUDGET', 'UPDATE_BUDGET']),
        catchError(err) {
            let error
            if ('name' in err) {
                error = get(() => err.name[0])
            } else if ('amount_cents' in err) {
                error = get(() => err.amount_cents[0])
            }
            this.loading = false
            this.error = error
        },
        initData({ name, amount_cents }) {
            this.name = name
            this.amount = toAmount(amount_cents)
        },
        async onClickCreate() {
            try {
                this.error = undefined
                this.loading = true
                await this.CREATE_BUDGET({
                    name: this.name,
                    amount_cents: toCents(this.amount),
                })
                this.$router.push({ name: 'Home' })
            } catch (err) {
                this.catchError(err)
            }
        },
        async onClickDelete() {
            if (!this.startDelete) {
                this.startDelete = true
            } else {
                try {
                    this.error = undefined
                    this.deleting = true
                    await this.DELETE_BUDGET(this.id)
                    this.$router.push({ name: 'Home' })
                } catch (err) {
                    this.resetDelete()
                    this.catchError(err)
                }
            }
        },
        async onClickUpdate() {
            try {
                this.error = undefined
                this.loading = true
                const data = {
                    ...this.budget,
                    name: this.name,
                    amount_cents: toCents(this.amount),
                }
                await this.UPDATE_BUDGET({ budgetId: this.id, data })
                this.$router.push({ name: 'Home' })
            } catch (err) {
                this.catchError(err)
            }
        },
        resetDelete() {
            this.startDelete = false
            this.deleting = false
        },
    },
    validations: {
        amount: {
            required,
            minValue: minValue(0),
        },
        name: {
            required,
        },
        validationGroup: ['amount', 'name'],
    },
    metaInfo() {
        return {
            title: this.title,
        }
    },
}
</script>

<style lang="scss" scoped>
@import '../../assets/styles/partials/variables';
@import '../../assets/styles/partials/functions';
@import '../../assets/styles/partials/mixins';

.budgets-form__footer {
    @include flex-row;
    justify-content: space-between;
    border-top: {
        color: #dedddc;
        style: solid;
        width: 1px;
    }
    padding: 1rem;
}
</style>
