// src/views/auth/Register.vue
<template>
    <Grid maxWidth="Md">
        <Row>
            <Column
                fluidHeight
                :bottomPadding="false"
                :md="6"
                :xs="12"
                :offset="{ md: 3 }"
            >
                <Box :mt="{ xs: 8, md: 12 }">
                    <Box :mb="1">
                        <Tex
                            size="Xl"
                            weight="Heavy"
                        >
                            Register an account
                        </Tex>
                    </Box>

                    <Box :mb="4">
                        <Tex size="Sm">
                            Been here before?
                            <Ref
                                color="Gray1"
                                decoration="Underline"
                                size="Sm"
                                :to="{ name: 'LogIn', query: { email: this.email }}"
                            >
                                Log in
                            </Ref>
                        </Tex>
                    </Box>

                    <Box
                        display="Flex"
                        el="Form"
                        flexDirection="Column"
                    >
                        <Box :mb="2">
                            <Field
                                v-model="email"
                                :isValid="!$v.email.$invalid"
                                autofocus
                                id="email"
                                label="Email"
                                showSuccess
                            />
                        </Box>

                        <Box :mb="2">
                            <Field
                                v-model="password"
                                :isValid="!$v.password.$invalid"
                                id="password"
                                label="Password"
                                showSuccess
                                type="Password"
                            />

                            <Box :mt="1.25">
                                <PasswordFeatures
                                    :hasLowercaseLetter="(password && $v.password.lowercase) || false"
                                    :hasUppercaseLetter="(password && $v.password.uppercase) || false"
                                    :hasNumber="(password && $v.password.digit) || false"
                                    :isMinLength="(password && $v.password.minLength) || false"
                                />
                            </Box>
                        </Box>

                        <Box :mb="2">
                            <Field
                                v-model="passwordConfirm"
                                :isValid="!$v.passwordConfirm.$invalid"
                                id="confirm-password"
                                label="Confirm Password"
                                showSuccess
                                type="Password"
                            />
                        </Box>

                        <Box fluidWidth>
                            <Button
                                color="Brand"
                                fluid
                                size="Lg"
                                textAlign="Left"
                                :disabled="$v.validationGroup.$invalid || loading"
                                :isLoading="loading"
                                :onClick="onClickRegister"
                            >
                                Sign Up
                            </Button>
                        </Box>

                        <Box :mt="1">
                            <Tex
                                color="Gray5"
                                size="Xxs"
                            >
                                By clicking this button, you agree to Wilbur’s
                                <Ref
                                    color="Gray5"
                                    decoration="Underline"
                                    size="Xxs"
                                    :to="{ name: 'Home' }"
                                >
                                    Terms of Use
                                </Ref>
                            </Tex>
                        </Box>

                        <Box
                            v-if="error"
                            :mt="3"
                        >
                            <Tex
                                color="Red3"
                                size="Sm"
                            >
                                {{ error }}
                            </Tex>
                        </Box>
                    </Box>
                </Box>
            </Column>
        </Row>
    </Grid>
</template>

<script>
import { mapActions } from 'vuex'
import {
    email,
    helpers,
    minLength,
    required,
    sameAs,
} from 'vuelidate/lib/validators'
import { get } from '@/utils'
import Box from '@/components/core/layout/Box'
import Button from '@/components/core/actions/Button'
import Column from '@/components/core/layout/Column'
import Field from '@/components/core/form/Field'
import Grid from '@/components/core/layout/Grid'
import PasswordFeatures from '@/components/ui/PasswordFeatures'
import Ref from '@/components/core/actions/Ref'
import Row from '@/components/core/layout/Row'
import Tex from '@/components/core/typography/Tex'

export default {
    name: 'Register',
    components: {
        Box,
        Button,
        Column,
        Field,
        Grid,
        PasswordFeatures,
        Ref,
        Row,
        Tex,
    },
    props: {
        emailParam: {
            type: String,
        },
    },
    data() {
        return {
            email: get(() => this.emailParam),
            error: undefined,
            loading: false,
            password: undefined,
            passwordConfirm: undefined,
        }
    },
    methods: {
        ...mapActions(['SIGN_UP_USER']),
        async onClickRegister() {
            this.error = undefined
            this.loading = true
            try {
                await this.SIGN_UP_USER({
                    email: this.email,
                    password: this.password,
                    passwordConfirm: this.passwordConfirm,
                })
                this.$router.push({ name: 'Home' })
            } catch (err) {
                let error
                if ('email' in err) {
                    error = get(() => err.email[0])
                } else if ('password' in err) {
                    error = get(() => err.password[0])
                }
                this.loading = false
                this.error = error
            }
        },
    },
    validations: {
        email: {
            email,
            required,
        },
        password: {
            digit: helpers.regex('digit', /^.*[0-9]+.*$/),
            lowercase: helpers.regex('lowercase', /^.*[a-z]+.*$/),
            minLength: minLength(8),
            required,
            uppercase: helpers.regex('uppercase', /^.*[A-Z]+.*$/),
        },
        passwordConfirm: {
            sameAs: sameAs('password'),
            required,
        },
        validationGroup: ['email', 'password', 'passwordConfirm'],
    },
    metaInfo: {
        title: 'Sign Up',
    },
}
</script>

// src/pages/auth/Register/index.tsx
import React from "react";
import { inject, observer } from "mobx-react";
import DocumentTitle from "react-document-title";
import {
    Box,
    Button,
    Col,
    Field,
    Grid,
    Link,
    PasswordFeatures,
    Row,
    Text
} from "../../../components";
import RootStore from "../../../store";
import { parse } from "query-string";
import { get } from "../../../lib/get";

interface Props {
    location: Location;
    rootStore: RootStore;
}

class RegisterClass extends React.Component<Props> {
    componentWillMount() {
        const {
            location,
            rootStore: {
                registerStore: { setEmail }
            }
        } = this.props;
        const queryParams = parse(location.search);
        const email = get(() => queryParams.email);
        if (email) setEmail(email);
    }

    componentWillUnmount() {
        this.props.rootStore.registerStore.reset();
    }

    onChangeEmail = (e: React.ChangeEvent<any>) => {
        this.props.rootStore.registerStore.setEmail(e.target.value);
    };

    onChangePassword = (e: React.ChangeEvent<any>) => {
        this.props.rootStore.registerStore.setPassword(e.target.value);
    };

    onChangeConfirmPassword = (e: React.ChangeEvent<any>) => {
        this.props.rootStore.registerStore.setPasswordConfirm(e.target.value);
    };

    onSubmit = (e: React.FormEvent) => {
        e.preventDefault();
        this.props.rootStore.registerStore.register();
    };

    render() {
        const {
            rootStore: {
                registerStore: {
                    email,
                    error,
                    isLoading,
                    password,
                    passwordConfirm,
                    validations
                }
            }
        } = this.props;
        return (
            <DocumentTitle title="Register | Wilbur">
                <Grid maxWidth="md">
                    <Row>
                        <Col
                            fluidHeight
                            bottomPadding={false}
                            md={6}
                            xs={12}
                            offset={{ md: 3 }}
                        >
                            <Box mt={{ xs: 8, md: 12 }}>
                                <Box mb={1}>
                                    <Text
                                        font={Text.Font.Title}
                                        size={Text.Size.Xxl}
                                    >
                                        Register an account
                                    </Text>
                                </Box>

                                <Box mb={4}>
                                    <Text>
                                        Been here before?{" "}
                                        <Link
                                            color={Link.Color.Gray1}
                                            decoration
                                            to={{
                                                pathname: "/login",
                                                search:
                                                    !!email && `?email=${email}`
                                            }}
                                        >
                                            Log in
                                        </Link>
                                    </Text>
                                </Box>

                                <Box
                                    display={Box.Display.Flex}
                                    el={Box.Element.Form}
                                    flexDirection={Box.FlexDirection.Column}
                                    onSubmit={this.onSubmit}
                                >
                                    <Box mb={2}>
                                        <Field
                                            autocomplete="username email"
                                            autofocus
                                            id="email"
                                            isValid={validations.email.valid}
                                            label="Email"
                                            showSuccess
                                            value={email}
                                            onChange={this.onChangeEmail}
                                        />
                                    </Box>

                                    <Box mb={2}>
                                        <Field
                                            autocomplete="new-password"
                                            id="password"
                                            isValid={validations.password.valid}
                                            label="Password"
                                            showSuccess
                                            type={Field.Type.Password}
                                            value={password}
                                            onChange={this.onChangePassword}
                                        />
                                        <Box mt={1.25}>
                                            <PasswordFeatures
                                                hasLowercaseLetter={
                                                    !!password &&
                                                    validations.password
                                                        .lowercase
                                                }
                                                hasUppercaseLetter={
                                                    !!password &&
                                                    validations.password
                                                        .uppercase
                                                }
                                                hasNumber={
                                                    !!password &&
                                                    validations.password.digit
                                                }
                                                isMinLength={
                                                    !!password &&
                                                    validations.password
                                                        .minLength
                                                }
                                            />
                                        </Box>
                                    </Box>

                                    <Box mb={2}>
                                        <Field
                                            autocomplete="new-password"
                                            id="confirmPassword"
                                            isValid={
                                                validations.passwordConfirm
                                                    .valid
                                            }
                                            label="Confirm Password"
                                            showSuccess
                                            type={Field.Type.Password}
                                            value={passwordConfirm}
                                            onChange={
                                                this.onChangeConfirmPassword
                                            }
                                        />
                                    </Box>

                                    <Box fluidWidth>
                                        <Button
                                            color={Button.Color.Brand}
                                            disabled={!validations.all.valid}
                                            fluid
                                            isLoading={isLoading}
                                            size={Button.Size.Lg}
                                            textAlign={Button.TextAlign.Left}
                                            type="submit"
                                        >
                                            Sign Up
                                        </Button>
                                    </Box>

                                    <Box mt={1}>
                                        <Text
                                            color={Text.Color.Gray5}
                                            size={Text.Size.Xs}
                                        >
                                            By clicking this button, you agree
                                            to Wilbur&#8217;s{" "}
                                            <Link
                                                color={Text.Color.Gray5}
                                                decoration
                                                size={Text.Size.Xs}
                                                to="/terms"
                                            >
                                                Terms of Use
                                            </Link>
                                            .
                                        </Text>
                                    </Box>

                                    {!!error && (
                                        <Box mt={3}>
                                            <Text color={Text.Color.Red3}>
                                                {error}
                                            </Text>
                                        </Box>
                                    )}
                                </Box>
                            </Box>
                        </Col>
                    </Row>
                </Grid>
            </DocumentTitle>
        );
    }
}

export const Register = inject("rootStore")(observer(RegisterClass));
