// src/components/core/components/form/Field/index.tsx
import * as React from "react";
import styled, { css } from "styled-components";
import { style } from "../../../utils/css";
import { Box } from "../../layout/Box";
import { cssFactory } from "../../../utils/styled-components";
import { Size } from "../../../types/text";
import { AnyColor as Color } from "../../../types/color";
import { Type } from "../../../types/field";
import { ReactComponent as IconSuccess } from "../../../../../assets/icons/input-success.svg";
import { ThemeConsumer } from "../../theme/ThemeConsumer";

interface Props {
    /**
     * Adds autocomplete.
     */
    autocomplete?: string;

    /**
     * Applies disabled styling to the button.
     */
    autofocus?: boolean;

    /**
     * Defaults to `Field.Color.Gold3`.
     */
    color: Color;

    /**
     * Sets error message.
     */
    error?: string;

    /**
     * Applies disabled styling to the button.
     */
    disabled: boolean;

    /**
     * HTML id property.
     */
    id?: string;

    /**
     * Sets if the field is valid.
     */
    isValid?: boolean;

    /**
     * Sets the label and placeholder.
     */
    label: string;

    /**
     * Callback function for field change.
     */
    onChange: ((e: React.ChangeEvent<any>) => void);

    /**
     * If valid, show success icon.
     */
    showSuccess?: boolean;

    /**
     * HTML `type` attribute. See [MDN docs](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes).
     */
    type: Type;

    /**
     * Sets the value.
     */
    value: string | number | undefined;
}

export class Field extends React.Component<Props> {
    public static Color = Color;
    public static Type = Type;

    public static defaultProps = {
        autofocus: false,
        color: Color.Gold3,
        disabled: false,
        type: Type.Text
    };

    state = {
        isTouched: false
    };

    public handleChange = (e: React.ChangeEvent<any>) => {
        if (this.props.onChange && typeof this.props.onChange === "function") {
            this.props.onChange(e);
        }
    };

    private onBlur = () => {
        if (!this.state.isTouched) this.setState({ isTouched: true });
    };

    public render() {
        const {
            autocomplete,
            autofocus,
            color,
            error,
            disabled,
            id,
            isValid,
            label,
            showSuccess,
            type,
            value
        } = this.props;
        const { isTouched } = this.state;

        const active = !!value || (isTouched && !!error);
        const inputProps = {
            active,
            color,
            disabled,
            id,
            type,
            value,
            autoComplete: autocomplete,
            autoFocus: autofocus,
            error: isTouched && error,
            onBlur: this.onBlur,
            onChange: this.handleChange,
            placeholder: active ? "" : label,
            spellCheck: false
        };

        if (type === Type.Textarea) {
            const textareaProps = { ...inputProps, rows: 5 };
            return (
                <StyledFieldset>
                    <StyledTextarea {...textareaProps} />
                </StyledFieldset>
            );
        }

        const labelProps = {
            active,
            error: isTouched && error,
            htmlFor: id
        };

        const numberInputProps = type === Type.Number && {
            step: 0.01
        };

        return (
            <StyledFieldset>
                <StyledLabel {...labelProps}>{error || label}</StyledLabel>
                <StyledInput {...inputProps} {...numberInputProps} />
                {showSuccess && isValid && (
                    <ThemeConsumer>
                        {theme => (
                            <Box
                                css={`
                                    right: 0.6rem;
                                    top: 0.8rem;
                                    fill: ${theme.colors.green3};
                                `}
                                position={Box.Position.Absolute}
                            >
                                <IconSuccess />
                            </Box>
                        )}
                    </ThemeConsumer>
                )}
            </StyledFieldset>
        );
    }
}

export const StyledFieldset = styled.div`
    display: flex;
    flex-direction: column;
    margin: 0;
    paddding: 0;
    position: relative;
`;

interface LabelProps {
    active?: boolean;
    error?: boolean | string;
    htmlFor?: string;
}

const labelStyles = cssFactory<LabelProps>(css)`
    ${props =>
        style(
            "color",
            props.error ? props.theme.colors.red2 : props.theme.colors.gray1
        )};
    ${style("backgroundColor", Color.White)};
    ${props => style("fontFamily", props.theme.text.getFont())};
    ${props => style("fontSize", props.theme.text.getSize(Size.Xs))};
    ${props => style("opacity", props.active ? 1 : 0)};
    padding: 0 0.45rem;
    ${props => style("pointerEvents", props.active ? "all" : "none")};
    position: absolute;
    left: 0.6rem;
    ${props => style("top", props.active ? "-0.5rem" : 0)};
    transition: color, opacity, top 125ms;
`;

const StyledLabel = styled.label`
    ${labelStyles}
`;

interface InputProps {
    color: Color;
    error?: boolean | string;
}

const sharedFieldStyles = cssFactory<InputProps>(css)`
    ${props =>
        style(
            "border",
            props.theme.field.getBorderStyle(
                Color.Gray8,
                props.theme.colors,
                !!props.error
            )
        )};
    ${props => style("borderRadius", props.theme.cornerRadii.default)};
    box-sizing: border-box;
    ${props => style("color", props.theme.colors[Color.Gray1])};
    ${props => style("fontFamily", props.theme.text.getFont())};
    ${props => style("fontSize", props.theme.text.getSize(Size.Md))};
    outline: 0;
    transition: border-color 125ms;
    width: 100%;
    &::-webkit-input-placeholder {
        ${props => style("color", props.theme.colors[Color.Gray6])};
    }
    &:focus {
        ${props =>
            style(
                "border",
                props.theme.field.getFocusStyles(
                    props.color,
                    props.theme.colors,
                    !!props.error
                )
            )};
    }
`;

const inputStyles = cssFactory<InputProps>(css)`
    ${sharedFieldStyles}
    height: 2.8125rem;
    ${props =>
        style(
            "padding",
            props.theme.units.getValues(props.theme.field.padding)
        )};
    
    &::-webkit-outer-spin-button,
    &::-webkit-inner-spin-button {
        -webkit-appearance: none;
        margin: 0;
    }
`;

export const StyledInput = styled.input`
    ${inputStyles}
`;

const textareaStyles = cssFactory<InputProps>(css)`
    ${sharedFieldStyles}
    ${props =>
        style("padding", props.theme.units.getValues([0.55, 0.5, 0.15, 0.5]))};
    resize: none;

    &[rows] {
        height: auto;
    }
`;

export const StyledTextarea = styled.textarea`
    ${textareaStyles}
`;

// src/components/core/form/Field/index.vue
<script>
import Box from '@/components/core/layout/Box'
import InputSuccessIcon from '@/assets/icons/input-success.svg'
import Theme from '@/components/theme'
import Field from './constants'
import {
    StyledFieldset,
    StyledLabel,
    StyledInput,
    StyledTextArea,
} from './styled-components'

export default {
    name: 'Field',
    functional: true,
    props: {
        /**
         * Sets autofocus.
         */
        autofocus: {
            default: false,
            type: Boolean,
        },
        /**
         * Sets icon and focused border color.
         */
        color: {
            default: 'Gold3',
            type: String,
            validator: value => value in Theme.Color,
        },
        /**
         * Sets error message.
         */
        error: {
            type: String,
        },
        /**
         * Sets HTML `for` and `id` attributes.
         */
        id: {
            required: true,
            type: String,
        },
        /**
         * Sets if the input is dirty.
         */
        isDirty: {
            type: Boolean,
        },
        /**
         * Sets if the input is valid.
         */
        isValid: {
            type: Boolean,
        },
        /**
         * Sets the label and placeholder.
         */
        label: {
            required: true,
            type: String,
        },
        /**
         * If valid, shows success icon.
         */
        showSuccess: {
            default: false,
            type: Boolean,
        },
        /**
         * Sets type.
         */
        type: {
            default: 'Text',
            type: String,
            validator: value => value in Field.Type,
        },
        /**
         * Sets value.
         * @model
         */
        value: {
            type: [Number, String],
        },
    },
    render(h, { props, listeners }) {
        const {
            id,
            autofocus,
            color,
            error,
            isDirty,
            isValid,
            label,
            showSuccess,
            type,
            value,
        } = props
        const { input } = listeners

        const active = !!value || (isDirty && error)
        const inputProps = {
            props: {
                active,
                color,
                error: isDirty && error,
            },
            attrs: {
                autofocus,
                id,
                type,
                placeholder: label,
                spellcheck: false,
            },
            domProps: {
                value,
            },
            on: {
                input(value) {
                    input(value)
                },
            },
        }

        if (Field.Type[type] === 'textarea') {
            const p = {
                ...inputProps,
                attrs: {
                    ...inputProps.attrs,
                    rows: 5,
                },
            }
            return (
                <StyledFieldset>
                    <StyledTextArea {...p} />
                </StyledFieldset>
            )
        }

        const labelProps = {
            props: {
                active,
                error: isDirty && error,
            },
            attrs: {
                for: id,
            },
        }

        return (
            <StyledFieldset>
                <StyledLabel {...labelProps}>{error || label}</StyledLabel>
                <StyledInput {...inputProps} />
                {showSuccess && isValid && (
                    <Box
                        position="Absolute"
                        css={`
                            right: 0.6rem;
                            top: 0.8rem;
                            fill: ${Theme.Color.Green3};
                        `}
                    >
                        <InputSuccessIcon />
                    </Box>
                )}
            </StyledFieldset>
        )
    },
}
</script>

<docs>
```jsx
<Field
    v-model="email"
    id="email"
    label="Email"
/>
```
</docs>
