// src/components/Field.vue
<template>
    <fieldset class="field">
        <template
            v-if="type === 'textarea'"
        >
            <textarea
                v-focus="autofocus"
                :id="id"
                :class="['field__input', {
                    'error': isTouched && error,
                }]"
                :placeholder="label"
                :type="type"
                :value="value"
                rows="5"
                spellcheck="false"
                @blur="isTouched = true"
                @input="onInput($event.target.value)"
            >
            </textarea>
        </template>
        <template v-else>
            <label
                :class="['field__label', {
                    'active': value || (isTouched && error),
                    'error': isTouched && error,
                }]"
                :for="id"
            >
                <template v-if="isTouched && error">{{error}}</template>
                <template v-else>{{label}}</template>
            </label>
            <input
                v-focus="autofocus"
                :id="id"
                :class="['field__input', {
                    'error': isTouched && error,
                }]"
                :placeholder="label"
                :type="type"
                :value="value"
                spellcheck="false"
                @blur="isTouched = true"
                @input="onInput($event.target.value)"
            >
            <template
                v-if="showSuccess"
            >
                <div
                    v-show="isValid"
                    class="field__success"
                >
                    <InputSuccessIcon />
                </div>
            </template>
        </template>
    </fieldset>
</template>

<script>
export default {
    name: 'Field',
    components: {
        InputSuccessIcon: () => import('../assets/icons/input-success.svg'),
    },
    props: {
        autofocus: {
            default: false,
            type: Boolean,
        },
        error: {
            type: String,
        },
        id: {
            required: true,
            type: String,
        },
        isValid: {
            type: Boolean,
        },
        label: {
            type: String,
        },
        placeholder: {
            type: String,
        },
        showSuccess: {
            type: Boolean,
            default: false,
        },
        type: {
            type: String,
            default: 'text',
        },
        value: {
            type: [Number, String],
        },
        onInput: {
            default(value) {
                this.$emit('input', value)
            },
            type: Function,
        },
    },
    data: () => ({
        isTouched: false,
    }),
}
</script>

<style lang="scss" scoped>
@import '../assets/styles/variables';
@import '../assets/styles/functions';
@import '../assets/styles/mixins';

.field {
    @include flex-column;
    border: 0;
    margin: {
        bottom: 1rem;
        left: 0;
        right: 0;
        top: 0;
    }
    padding: 0;
    position: relative;

    &.checkbox {
        @include flex-row;
        margin-top: 0.25rem;
    }
}

.field__label {
    color: color(default, font, label);
    background-color: color(default, background);
    font: {
        family: $font-sans-serif;
        size: 0.7rem;
    }
    padding: {
        left: 0.45rem;
        right: 0.45rem;
    }
    opacity: 0;
    pointer-events: none;
    position: absolute;
    left: 0.6rem;
    top: 0;
    transition: {
        duration: $transition-duration / 2;
        property: color, opacity, top;
    }

    &.active {
        opacity: 1;
        pointer-events: all;
        top: -0.4rem;
    }

    &.error {
        color: color(default, font, error);
    }
}

.field__input {
    border: {
        color: color(default, border);
        radius: $border-radius;
        style: solid;
        width: 1px;
    }
    color: color(default, font);
    font: {
        family: $font-sans-serif;
        size: 0.9rem;
    }
    height: 2.5rem;
    outline: 0;
    padding: {
        bottom: 0;
        left: 1rem;
        right: 0;
        top: 0.15rem;
    }
    transition: {
        duration: $transition-duration;
        property: border-color, box-shadow;
    }
    width: 100%;

    &::-webkit-input-placeholder {
        color: color(default, font, placeholder);
    }

    &::-webkit-outer-spin-button,
    &::-webkit-inner-spin-button {
        -webkit-appearance: none;
        margin: 0;
    }

    &:focus {
        border-color: color(default, border, active);
    }

    &.error {
        border-color: color(default, border, error);
        color: color(default, font, error);
    }
}

textarea.field__input {
    padding: {
        bottom: 0.15rem;
        top: 0.7rem;
    }
    resize: none;
    width: 100% !important;

    &[rows] {
        height: auto;
    }
}

.field__success {
    position: absolute;
    right: 1rem;
    top: 0.75rem;
}
</style>

// src/components/core/components/form/Field/index.tsx
import * as React from "react";
import styled, { css } from "styled-components";
import { style } from "../../../utils/css";
import { Box } from "../../layout/Box";
import { cssFactory } from "../../../utils/styled-components";
import { Size } from "../../../types/text";
import { AnyColor as Color } from "../../../types/color";
import { Type } from "../../../types/field";
import { ReactComponent as IconSuccess } from "../../../../../assets/icons/input-success.svg";
import { ThemeConsumer } from "../../theme/ThemeConsumer";

interface Props {
    /**
     * Adds autocomplete.
     */
    autocomplete?: string;

    /**
     * Applies disabled styling to the button.
     */
    autofocus?: boolean;

    /**
     * Defaults to `Field.Color.Gold3`.
     */
    color: Color;

    /**
     * Sets error message.
     */
    error?: string;

    /**
     * Applies disabled styling to the button.
     */
    disabled: boolean;

    /**
     * HTML id property.
     */
    id?: string;

    /**
     * Sets if the field is valid.
     */
    isValid?: boolean;

    /**
     * Sets the label and placeholder.
     */
    label: string;

    /**
     * Callback function for field change.
     */
    onChange: ((e: React.ChangeEvent<any>) => void);

    /**
     * If valid, show success icon.
     */
    showSuccess?: boolean;

    /**
     * HTML `type` attribute. See [MDN docs](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes).
     */
    type: Type;

    /**
     * Sets the value.
     */
    value: string | number | undefined;
}

export class Field extends React.Component<Props> {
    public static Color = Color;
    public static Type = Type;

    public static defaultProps = {
        autofocus: false,
        color: Color.Gold3,
        disabled: false,
        type: Type.Text
    };

    state = {
        isTouched: false
    };

    public handleChange = (e: React.ChangeEvent<any>) => {
        if (this.props.onChange && typeof this.props.onChange === "function") {
            this.props.onChange(e);
        }
    };

    private onBlur = () => {
        if (!this.state.isTouched) this.setState({ isTouched: true });
    };

    public render() {
        const {
            autocomplete,
            autofocus,
            color,
            error,
            disabled,
            id,
            isValid,
            label,
            showSuccess,
            type,
            value
        } = this.props;
        const { isTouched } = this.state;

        const active = !!value || (isTouched && !!error);
        const inputProps = {
            active,
            color,
            disabled,
            id,
            type,
            value,
            autoComplete: autocomplete,
            autoFocus: autofocus,
            error: isTouched && error,
            onBlur: this.onBlur,
            onChange: this.handleChange,
            placeholder: active ? "" : label,
            spellCheck: false
        };

        if (type === Type.Textarea) {
            const textareaProps = { ...inputProps, rows: 5 };
            return (
                <StyledFieldset>
                    <StyledTextarea {...textareaProps} />
                </StyledFieldset>
            );
        }

        const labelProps = {
            active,
            error: isTouched && error,
            htmlFor: id
        };

        const numberInputProps = type === Type.Number && {
            step: 0.01
        };

        return (
            <StyledFieldset>
                <StyledLabel {...labelProps}>{error || label}</StyledLabel>
                <StyledInput {...inputProps} {...numberInputProps} />
                {showSuccess && isValid && (
                    <ThemeConsumer>
                        {theme => (
                            <Box
                                css={`
                                    right: 0.6rem;
                                    top: 0.8rem;
                                    fill: ${theme.colors.green3};
                                `}
                                position={Box.Position.Absolute}
                            >
                                <IconSuccess />
                            </Box>
                        )}
                    </ThemeConsumer>
                )}
            </StyledFieldset>
        );
    }
}

export const StyledFieldset = styled.div`
    display: flex;
    flex-direction: column;
    margin: 0;
    paddding: 0;
    position: relative;
`;

interface LabelProps {
    active?: boolean;
    error?: boolean | string;
    htmlFor?: string;
}

const labelStyles = cssFactory<LabelProps>(css)`
    ${props =>
        style(
            "color",
            props.error ? props.theme.colors.red2 : props.theme.colors.gray1
        )};
    ${props => style("backgroundColor", props.theme.colors.white)};
    background-image: ${props =>
        `linear-gradient(to bottom, ${props.theme.colors.background} 45%, ${
            props.theme.colors.white
        } 45%)`};
    ${props => style("fontFamily", props.theme.text.getFont())};
    ${props => style("fontSize", props.theme.text.getSize(Size.Xs))};
    ${props => style("opacity", props.active ? 1 : 0)};
    padding: 0 0.45rem;
    ${props => style("pointerEvents", props.active ? "all" : "none")};
    position: absolute;
    left: 0.6rem;
    ${props => style("top", props.active ? "-0.5rem" : 0)};
    transition: color, opacity, top 125ms;
`;

const StyledLabel = styled.label`
    ${labelStyles}
`;

interface InputProps {
    color: Color;
    error?: boolean | string;
}

const sharedFieldStyles = cssFactory<InputProps>(css)`
    ${props =>
        style(
            "border",
            props.theme.field.getBorderStyle(
                Color.Gray8,
                props.theme.colors,
                !!props.error
            )
        )};
    ${props => style("borderRadius", props.theme.cornerRadii.default)};
    box-sizing: border-box;
    ${props => style("color", props.theme.colors[Color.Gray1])};
    ${props => style("fontFamily", props.theme.text.getFont())};
    ${props => style("fontSize", props.theme.text.getSize(Size.Md))};
    outline: 0;
    transition: border-color 125ms;
    width: 100%;
    &::-webkit-input-placeholder {
        ${props => style("color", props.theme.colors[Color.Gray6])};
    }
    &:focus {
        ${props =>
            style(
                "border",
                props.theme.field.getFocusStyles(
                    props.color,
                    props.theme.colors,
                    !!props.error
                )
            )};
    }
`;

const inputStyles = cssFactory<InputProps>(css)`
    ${sharedFieldStyles}
    height: 2.8125rem;
    ${props =>
        style(
            "padding",
            props.theme.units.getValues(props.theme.field.padding.input)
        )};
    
    &::-webkit-outer-spin-button,
    &::-webkit-inner-spin-button {
        -webkit-appearance: none;
        margin: 0;
    }
`;

export const StyledInput = styled.input`
    ${inputStyles}
`;

const textareaStyles = cssFactory<InputProps>(css)`
    ${sharedFieldStyles}
    ${props =>
        style(
            "padding",
            props.theme.units.getValues(props.theme.field.padding.textarea)
        )};
    resize: none;

    &[rows] {
        height: auto;
    }
`;

export const StyledTextarea = styled.textarea`
    ${textareaStyles}
`;
